# Template:
[![acele-happy](https://circleci.com/gh/acele-happy/ATPL_Portifolio_Backed.svg?style=shield)](https://app.circleci.com/pipelines/github/acele-happy)

# Example:
[![CircleCI](https://circleci.com/gh/circleci/circleci-docs.svg?style=svg)](https://circleci.com/gh/circleci/circleci-docs)

# Example for specific branch:
[![CircleCI](https://circleci.com/gh/circleci/circleci-docs/tree/teesloane-patch-5.svg?style=svg)](https://circleci.com/gh/circleci/circleci-docs/?branch=teesloane-patch-5)
